server:
  port: 8210
spring:
  profiles:
    active: dev
  redis:
    host: 39.106.192.131
    port: 6379
    password: "momik2019redis.."
    database: 0
    timeout: 1800ms #连接超时时间
    lettuce:
      pool:
        max-active: 8 #连接池最大连接数（使用负值表示没有限制） 默认 8
        max-idle: 8 #连接池中的最大空闲连接 默认 8
        max-wait: -1ms #连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        min-idle: 0 #连接池中的最小空闲连接 默认 0
